sudo: false
language: node_js
sudo: required
dist: trusty
node_js:
  - "6"
  - "5"
  - "4"
before_install: 
  - sudo add-apt-repository -y ppa:mc3man/trusty-media
  - sudo apt-get -qq update
  - sudo apt-get install -y ffmpeg
  - ffmpeg -version
install: ./travis-install-dependencies.sh
script: ./travis-build.sh
branches:
  only:
    - "master"
cache:
  directories:
  - node_modules
  - typings

notifications:
  email: false