sudo: false
language: node_js
node_js:
  - "6"
  - "5"
  - "4"
install: ./travis-install-dependencies.sh
script: ./travis-build.sh
branches:
  only:
    - "master"
cache:
  directories:
  - node_modules
  - typings